#!/usr/bin/env python3
# genttf.py -- bundle a TrueType face into flash as a CP1252 subset.
#
# The on-device rasterizer (stb_truetype) only ever needs the CP1252 charset, so we
# subset the source TTF to those code points before embedding it. That drops a ~700 KB
# DejaVu face to ~60-80 KB -- essential, since the app partition is 4 MB and nearly full.
#
# The subset PRESERVES per-glyph advance widths (the hmtx table is kept for the retained
# glyphs), so the companion -- which lays text out with PIL against its own full copy of
# the same face -- gets byte-identical advances on the wall. That is the whole metrics
# contract; subsetting is transparent to it. (Hinting is dropped: we rasterize grayscale
# coverage at arbitrary sizes, no grid-fitting.)
#
# Usage:  genttf.py <src.ttf> <c_var_name> <out.cpp>
# Emits:  const unsigned char <var>[]; const unsigned int <var>_len;

import sys, os, tempfile

def cp1252_unicodes():
    us = set()
    for b in range(0x20, 0x100):
        try:
            us.add(ord(bytes([b]).decode('cp1252')))
        except UnicodeDecodeError:
            pass                       # 0x81 0x8D 0x8F 0x90 0x9D are undefined in cp1252
    return sorted(us)

def main():
    if len(sys.argv) != 4:
        print("usage: genttf.py <src.ttf> <var_name> <out.cpp>"); sys.exit(2)
    src, var, out = sys.argv[1], sys.argv[2], sys.argv[3]
    us = cp1252_unicodes()
    unis = ",".join("U+%04X" % u for u in us)
    fd, sub = tempfile.mkstemp(suffix=".ttf"); os.close(fd)
    from fontTools.subset import main as subset_main
    subset_main([src, "--unicodes=" + unis, "--output-file=" + sub,
                 "--no-hinting", "--desubroutinize", "--notdef-outline",
                 "--drop-tables+=DSIG,GPOS,GSUB,GDEF,kern,LTSH,hdmx,VDMX,gasp"])
    data = open(sub, "rb").read(); os.unlink(sub)
    with open(out, "w") as f:
        f.write("// Generated by tools/genttf.py -- do not edit by hand.\n")
        f.write("// CP1252 subset of %s: %d glyphs, %d bytes.\n"
                % (os.path.basename(src), len(us), len(data)))
        f.write("// Advance metrics preserved -> matches the companion's PIL layout.\n")
        f.write("#include <stdint.h>\n\n")
        f.write("extern const unsigned int %s_len;\n" % var)
        f.write("const unsigned int %s_len = %d;\n" % (var, len(data)))
        f.write("extern const unsigned char %s[];\n" % var)
        f.write("const unsigned char %s[] = {\n" % var)
        for i in range(0, len(data), 20):
            f.write("  " + ",".join(str(x) for x in data[i:i+20]) + ",\n")
        f.write("};\n")
    print("wrote %s: %d glyphs, %d bytes (from %d)" % (out, len(us), len(data), os.path.getsize(src)))

if __name__ == "__main__":
    main()
