// fontflap.h -- GENERATED by tools/genflapfont.py; do not edit by hand.
// The BIG flap face for the LCD surface: Helvetica Bold rendered into a monospaced
// 72x100 1-bit box, byte-packed rows (MSB = leftmost), one shared baseline.
// Glyph order is IDENTICAL to font1252 (230 glyphs: CP1252 then the pictographs),
// so FONT1252_INDEX and reelGlyph() resolve indices for both faces.
#pragma once
#include <stdint.h>

#define FONTFLAP_W   72
#define FONTFLAP_H   100
#define FONTFLAP_BPR 9
#define FONTFLAP_N   230

extern const uint8_t FONTFLAP_BITS[FONTFLAP_N][FONTFLAP_H * FONTFLAP_BPR];
