// fontflap.h -- GENERATED by tools/genflapfont.py; do not edit by hand.
// The Helvetica flap faces for the LCD surface: monospaced 1-bit boxes, byte-packed
// rows (MSB = leftmost), one shared baseline per face. Glyph order is IDENTICAL to
// font1252 (230 glyphs: CP1252 then the pictographs), so FONT1252_INDEX and
// reelGlyph() resolve indices for every face. FONTFLAP_FACES is largest-first;
// dispPlan picks the first face whose box fits the cell.
#pragma once
#include <stdint.h>

#define FONTFLAP_N        230
#define FONTFLAP_FACE_CNT 2
#define FONTFLAP_MAX_W    72

struct FlapFace {
  uint16_t       w, h, bpr;   // glyph box and bytes per packed row
  const uint8_t* bits;        // glyph gi at bits[gi * h * bpr]
};
extern const FlapFace FONTFLAP_FACES[FONTFLAP_FACE_CNT];
